language: python
python: "2.7"
before_install:
install:
  - pip install zc.buildout
  - buildout init
  - bin/buildout -N -t 3 -c travis.cfg
script: bin/test -s younglives.publication
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
